MorphSVGPlugin.convertToPath("polygon");var xmlns="http://www.w3.org/2000/svg",xlinkns="http://www.w3.org/1999/xlink";select=function(a){return document.querySelector(a)};selectAll=function(a){return document.querySelectorAll(a)};pContainer=select(".pContainer");mainSVG=select(".mainSVG");star=select("#star");sparkle=select(".sparkle");tree=select("#tree");showParticle=!0;particleColorArray="#E8F6F8 #ACE8F8 #F6FBFE #A2CBDC #B74551 #5DBA72 #910B28 #910B28 #446D39".split(" ");
particleTypeArray=["#star","#circ","#cross","#heart"];particleTypeArray=["#star"];particlePool=[];particleCount=0;numParticles=200;TweenMax.set("svg",{visibility:"visible"});TweenMax.set(sparkle,{transformOrigin:"50% 50%",y:-100});var treePath=MorphSVGPlugin.pathDataToBezier(select(".treePath").getAttribute("d"),{offsetX:0,offsetY:-5}),treeBottomPath=MorphSVGPlugin.pathDataToBezier(select(".treeBottomPath").getAttribute("d"),{offsetX:0,offsetY:-5}),mainTl=new TimelineMax({delay:2,repeat:-1}),starTl;
function randomBetween(a,b){return Math.floor(Math.random()*(b-a+1)+a)}function flicker(a){TweenMax.killTweensOf(a,{opacity:!0});TweenMax.fromTo(a,.07,{alpha:1},{alpha:Math.random(),repeat:-1})}
function createParticles(){for(var a=numParticles,b;-1<--a;)b=select(particleTypeArray[a%particleTypeArray.length]).cloneNode(!0),mainSVG.appendChild(b),b.setAttribute("fill",particleColorArray[a%particleColorArray.length]),b.setAttribute("class","particle"),particlePool.push(b),TweenMax.set(b,{x:-100,y:-100,transformOrigin:"50% 50%"})}function getScale(){return randomBetween(5,20)/10}
function playParticle(a){showParticle&&(a=particlePool[particleCount],TweenMax.set(a,{x:pContainer._gsTransform.x,y:pContainer._gsTransform.y,scale:getScale()}),(new TimelineMax).to(a,randomBetween(10,60)/10,{physics2D:{velocity:randomBetween(-13,16),angle:randomBetween(-180,180),gravity:randomBetween(-13,44)},scale:0,rotation:randomBetween(-123,360),ease:Power1.easeOut,onStart:flicker,onStartParams:[a],onRepeat:function(b){TweenMax.set(b,{scale:getScale()})},onRepeatParams:[a]}),particleCount++,
particleCount=particleCount>=numParticles?0:particleCount)}
function drawStar(){starTl=new TimelineMax({onUpdate:playParticle});starTl.to([pContainer,sparkle],6,{bezier:{type:"cubic",values:treePath,autoRotate:!1},ease:Linear.easeNone}).to([pContainer,sparkle],1,{onStart:function(){showParticle=!1},x:treeBottomPath[0].x,y:treeBottomPath[0].y}).to([pContainer,sparkle],2,{onStart:function(){showParticle=!0},bezier:{type:"cubic",values:treeBottomPath,autoRotate:!1},ease:Linear.easeNone},"-=0").from(".treeBottomMask",2,{drawSVG:"0% 0%",stroke:"#FFF",ease:Linear.easeNone},
"-=2")}function textAnim(){}createParticles();drawStar();
mainTl.staggerFrom([".treePathMask",".treePotMask",".treeBottomMask"],6,{drawSVG:"0% 0%",stroke:"#FFF",cycle:{duration:[6,1,2]},ease:Linear.easeNone},6).from(".treeStar",3,{scaleY:0,scaleX:.15,transformOrigin:"50% 50%",ease:Elastic.easeOut.config(1,.5)},"-=4").to([".treeStarOutline",".messageText"],1,{alpha:1,ease:RoughEase.ease.config({template:Power0.easeNone,strength:2,points:16,taper:"none",randomize:!0,clamp:!1})},"-=3").to(sparkle,3,{alpha:0,ease:RoughEase.ease.config({template:Power0.easeNone,
strength:2,points:100,taper:"both",randomize:!0,clamp:!1})},"-=5").to(".whole",2,{alpha:0,ease:Sine.easeIn},"+=2");mainTl.add(starTl,0);TweenMax.globalTimeScale(1.5);